# -*- coding: utf-8 -*-
"""
Created on Fri Mar 27 19:04:49 2020

@author: Cheeku
"""

import bs4
import pymongo
import pandas as pd
#from urllib.request import urlopen as uReq
from urllib.request import Request, urlopen
import pygal
from bs4 import BeautifulSoup as soup

my_url = "https://www.worldometers.info/coronavirus/#countries"
req = Request(my_url, headers={'User-Agent': 'Mozilla/5.0'})
#uClient = uReq(my_url)
page_html = urlopen(req).read()
#req.close()
#print(page_html)

ps = soup(page_html,"html.parser")
table = ps.findAll("table")
df = pd.read_html(str(table))
'''
ps2 = soup(page_html,"html.parser")
table2 = ps.findAll("tr", attrs = {"class" : "total+row"})
dfx = pd.read_html(str(table2)) 
print(dfx)
'''
df[1] = df[1].drop('Tot Cases/1M pop', 1)
df[1] = df[1].drop('ActiveCases', 1)
df[1] = df[1].drop('Serious,Critical', 1)
df[1] = df[1].drop('Deaths/1M pop', 1)
df[1] = df[1].drop('TotalTests', 1)
#df[1] = df[1].drop('Tests/1M pop', 1)

df[1]["TotalCases"] = df[1]["TotalCases"].fillna(0)
for i in df[1]["TotalCases"]:
    k='0'
    i = str(i).split("+")
    for x in i:
        k+=x
    j='0'
    i = str(k).split(",")
    for x in i: 
        j+=x 
    i = int(j)


df[1]["TotalDeaths"] = df[1]["TotalDeaths"].fillna(0)
for i in df[1]["TotalDeaths"]:
    k='0'
    i = str(i).split("+")
    for x in i:
        k+=x
    j='0'
    i = str(k).split(",")
    for x in i: 
        j+=x
    i=j.split('.')[0]
    i = int(i)

df[1]["TotalRecovered"] = df[1]["TotalRecovered"].fillna(0)
for i in df[1]["TotalRecovered"]:
    k='0'
    i = str(i).split("+")
    for x in i:
        k+=x
    j='0'
    i = str(k).split(",")
    for x in i: 
        j+=x
    i=j.split('.')[0]
    i = int(i)


#df2 = str(df[1]) 
print(df[1])
print(max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "World").fillna(0)))

tc = pygal.maps.world.World()
tc.title = 'Total Cases'
tc.add(str(int(max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "World").fillna(0)))) , {
		'ad':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Andorra").fillna(0)), 
		'ae':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "UAE").fillna(0)), 
		'af':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Afghanistan").fillna(0)), 
		'al':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Albania").fillna(0)), 
		'am':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Armenia").fillna(0)), 
		'ao':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Angola").fillna(0)), 
#		'aq':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Antarctica").fillna(0)), 
		'ar':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Argentina").fillna(0)), 
		'at':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Austria").fillna(0)), 
		'au':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Australia").fillna(0)), 
		'az':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Azerbaijan").fillna(0)), 
		'ba':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Bosnia and Herzegovina").fillna(0)), 
		'bd':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Bangladesh").fillna(0)), 
		'be':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Belgium").fillna(0)), 
		'bf':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Burkina Faso").fillna(0)), 
		'bg':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Bulgaria").fillna(0)), 
		'bh':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Bahrain").fillna(0)), 
		#'bi':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Burundi").fillna(0)), 
		'bj':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Benin").fillna(0)), 
		'bn':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Brunei").fillna(0)), 
		'bo':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Bolivia").fillna(0)), 
		'br':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Brazil").fillna(0)), 
		'bt':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Bhutan").fillna(0)), 
		'bw':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Botswana").fillna(0)), 
		'by':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Belarus").fillna(0)), 
		'bz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Belize").fillna(0)), 
		'ca':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Canada").fillna(0)), 
#		'cd':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Congo").fillna(0)), 
#		'cf':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Central African Republic").fillna(0)), 
		'cg':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Congo").fillna(0)), 
		'ch':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Switzerland").fillna(0)), 
#		'ci':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Cote d’Ivoire").fillna(0)), 
		'cl':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Chile").fillna(0)), 
		'cm':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Cameroon").fillna(0)), 
		'cn':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "China").fillna(0)), 
		'co':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Colombia").fillna(0)), 
		'cr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Costa Rica").fillna(0)), 
		'cu':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Cuba").fillna(0)), 
#		'cv':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Cape Verde").fillna(0)), 
		'cy':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Cyprus").fillna(0)), 
		'cz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Czechia").fillna(0)), 
		'de':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Germany").fillna(0)), 
		'dj':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Djibouti").fillna(0)), 
		'dk':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Denmark").fillna(0)), 
		'do':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Dominican Republic").fillna(0)), 
		'dz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Algeria").fillna(0)), 
		'ec':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Ecuador").fillna(0)), 
		'ee':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Estonia").fillna(0)), 
		'eg':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Egypt").fillna(0)), 
#		'eh':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Western Sahara").fillna(0)), 
		'er':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Eritrea").fillna(0)), 
		'es':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Spain").fillna(0)), 
		'et':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Ethiopia").fillna(0)), 
		'fi':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Finland").fillna(0)), 
		'fr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "France").fillna(0)), 
		'ga':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Gabon").fillna(0)), 
		'gb':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "UK").fillna(0)), 
		'ge':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Georgia").fillna(0)), 
		'gf':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "French Guiana").fillna(0)), 
		'gh':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Ghana").fillna(0)), 
		'gl':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Greenland").fillna(0)), 
		'gm':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Gambia").fillna(0)), 
		'gn':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Guinea").fillna(0)), 
		'gq':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Equatorial Guinea").fillna(0)), 
		'gr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Greece").fillna(0)), 
		'gt':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Guatemala").fillna(0)), 
#		'gu':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Guam").fillna(0)), 
		'gw':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Guinea-Bissau").fillna(0)), 
		'gy':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Guyana").fillna(0)), 
		'hk':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Hong Kong").fillna(0)), 
		'hn':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Honduras").fillna(0)), 
		'hr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Croatia").fillna(0)), 
		'ht':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Haiti").fillna(0)), 
		'hu':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Hungary").fillna(0)), 
		'id':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Indonesia").fillna(0)), 
		'ie':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Ireland").fillna(0)), 
		'il':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Israel").fillna(0)), 
		'in':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "India").fillna(0)), 
		'iq':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Iraq").fillna(0)), 
		'ir':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Iran").fillna(0)), 
		'is':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Iceland").fillna(0)), 
		'it':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Italy").fillna(0)), 
		'jm':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Jamaica").fillna(0)), 
		'jo':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Jordan").fillna(0)), 
		'jp':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Japan").fillna(0)), 
		'ke':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Kenya").fillna(0)), 
		'kg':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Kyrgyzstan").fillna(0)), 
		'kh':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Cambodia").fillna(0)), 
		#'kp':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Korea, Democratic People’s Republic of").fillna(0)), 
		'kr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "S. Korea").fillna(0)), 
		'kw':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Kuwait").fillna(0)), 
		'kz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Kazakhstan").fillna(0)), 
		'la':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Laos").fillna(0)), 
		'lb':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Lebanon").fillna(0)), 
		'li':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Liechtenstein").fillna(0)), 
		'lk':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Sri Lanka").fillna(0)), 
		'lr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Liberia").fillna(0)), 
		#'ls':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Lesotho").fillna(0)), 
		'lt':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Lithuania").fillna(0)), 
		'lu':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Luxembourg").fillna(0)), 
		'lv':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Latvia").fillna(0)), 
		'ly':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Libya").fillna(0)), 
		'ma':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Morocco").fillna(0)), 
		'mc':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Monaco").fillna(0)), 
		'md':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Moldova").fillna(0)), 
		'me':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Montenegro").fillna(0)), 
		'mg':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Madagascar").fillna(0)), 
		'mk':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "North Macedonia").fillna(0)), 
		'ml':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Mali").fillna(0)), 
		'mm':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Myanmar").fillna(0)), 
		'mn':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Mongolia").fillna(0)), 
		'mo':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Macao").fillna(0)), 
		'mr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Mauritania").fillna(0)), 
		'mt':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Malta").fillna(0)), 
		'mu':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Mauritius").fillna(0)), 
		'mv':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Maldives").fillna(0)), 
#		'mw':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Malawi").fillna(0)), 
		'mx':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Mexico").fillna(0)), 
		'my':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Malaysia").fillna(0)), 
		'mz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Mozambique").fillna(0)), 
		'na':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Namibia").fillna(0)), 
		'ne':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Niger").fillna(0)), 
		'ng':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Nigeria").fillna(0)), 
		'ni':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Nicaragua").fillna(0)), 
		'nl':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Netherlands").fillna(0)), 
		'no':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Norway").fillna(0)), 
		'np':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Nepal").fillna(0)), 
		'nz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "New Zealand").fillna(0)), 
		'om':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Oman").fillna(0)), 
		'pa':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Panama").fillna(0)), 
		'pe':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Peru").fillna(0)), 
		'pg':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Papua New Guinea").fillna(0)), 
		'ph':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Philippines").fillna(0)), 
		'pk':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Pakistan").fillna(0)), 
		'pl':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Poland").fillna(0)), 
#		'pr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Puerto Rico").fillna(0)), 
		'ps':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Palestine").fillna(0)), 
		'pt':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Portugal").fillna(0)), 
		'py':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Paraguay").fillna(0)), 
		're':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Réunion").fillna(0)), 
		'ro':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Romania").fillna(0)), 
		'rs':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Serbia").fillna(0)), 
		'ru':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Russia").fillna(0)), 
		'rw':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Rwanda").fillna(0)), 
		'sa':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Saudi Arabia").fillna(0)), 
		'sc':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Seychelles").fillna(0)), 
		'sd':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Sudan").fillna(0)), 
		'se':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Sweden").fillna(0)), 
		'sg':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Singapore").fillna(0)), 
		'sh':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Saint Kitts and Nevis").fillna(0)), 
		'si':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Slovenia").fillna(0)), 
		'sk':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Slovakia").fillna(0)), 
		'sl':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Sierra Leone").fillna(0)), 
		'sm':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "San Marino").fillna(0)), 
		'sn':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Senegal").fillna(0)), 
		'so':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Somalia").fillna(0)), 
		'sr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Suriname").fillna(0)), 
		#'st':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Sao Tome and Principe").fillna(0)), 
		'sv':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "El Salvador").fillna(0)), 
		'sy':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Syria").fillna(0)), 
#		'sz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Swaziland").fillna(0)), 
		'td':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Chad").fillna(0)), 
		'tg':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Togo").fillna(0)), 
		'th':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Thailand").fillna(0)), 
#		'tj':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Tajikistan").fillna(0)), 
		'tl':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Timor-Leste").fillna(0)), 
	#	'tm':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Turkmenistan").fillna(0)), 
		'tn':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Tunisia").fillna(0)), 
		'tr':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Turkey").fillna(0)), 
		'tw':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Taiwan").fillna(0)), 
		'tz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Tanzania").fillna(0)), 
		'ua':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Ukraine").fillna(0)), 
		'ug':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Uganda").fillna(0)), 
		'us':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "USA").fillna(0)), 
		'uy':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Uruguay").fillna(0)), 
		'uz':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Uzbekistan").fillna(0)), 
		'va':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Vatican City").fillna(0)), 
		've':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Venezuela").fillna(0)), 
		'vn':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Vietnam").fillna(0)), 
		#'ye':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Yemen").fillna(0)), 
		'yt':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Mayotte").fillna(0)), 
		'za':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "South Africa").fillna(0)), 
		'zm':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Zambia").fillna(0)), 
		'zw':max(df[1]['TotalCases'].where(df[1]['Country,Other'] == "Zimbabwe").fillna(0))
        
        })

tc.render_to_file('TotalCases.svg')



tc1 = pygal.maps.world.World()
tc1.title = 'Total Deaths'
tc1.add(str(int(max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "World").fillna(0)))) , {
		'ad':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Andorra").fillna(0)), 
		'ae':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "UAE").fillna(0)), 
		'af':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Afghanistan").fillna(0)), 
		'al':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Albania").fillna(0)), 
		'am':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Armenia").fillna(0)), 
		'ao':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Angola").fillna(0)), 
#		'aq':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Antarctica").fillna(0)), 
		'ar':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Argentina").fillna(0)), 
		'at':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Austria").fillna(0)), 
		'au':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Australia").fillna(0)), 
		'az':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Azerbaijan").fillna(0)), 
		'ba':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Bosnia and Herzegovina").fillna(0)), 
		'bd':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Bangladesh").fillna(0)), 
		'be':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Belgium").fillna(0)), 
		'bf':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Burkina Faso").fillna(0)), 
		'bg':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Bulgaria").fillna(0)), 
		'bh':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Bahrain").fillna(0)), 
		#'bi':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Burundi").fillna(0)), 
		'bj':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Benin").fillna(0)), 
		'bn':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Brunei").fillna(0)), 
		'bo':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Bolivia").fillna(0)), 
		'br':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Brazil").fillna(0)), 
		'bt':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Bhutan").fillna(0)), 
		'bw':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Botswana").fillna(0)), 
		'by':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Belarus").fillna(0)), 
		'bz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Belize").fillna(0)), 
		'ca':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Canada").fillna(0)), 
#		'cd':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Congo").fillna(0)), 
#		'cf':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Central African Republic").fillna(0)), 
		'cg':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Congo").fillna(0)), 
		'ch':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Switzerland").fillna(0)), 
#		'ci':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Cote d’Ivoire").fillna(0)), 
		'cl':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Chile").fillna(0)), 
		'cm':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Cameroon").fillna(0)), 
		'cn':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "China").fillna(0)), 
		'co':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Colombia").fillna(0)), 
		'cr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Costa Rica").fillna(0)), 
		'cu':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Cuba").fillna(0)), 
#		'cv':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Cape Verde").fillna(0)), 
		'cy':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Cyprus").fillna(0)), 
		'cz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Czechia").fillna(0)), 
		'de':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Germany").fillna(0)), 
		'dj':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Djibouti").fillna(0)), 
		'dk':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Denmark").fillna(0)), 
		'do':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Dominican Republic").fillna(0)), 
		'dz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Algeria").fillna(0)), 
		'ec':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Ecuador").fillna(0)), 
		'ee':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Estonia").fillna(0)), 
		'eg':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Egypt").fillna(0)), 
#		'eh':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Western Sahara").fillna(0)), 
		'er':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Eritrea").fillna(0)), 
		'es':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Spain").fillna(0)), 
		'et':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Ethiopia").fillna(0)), 
		'fi':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Finland").fillna(0)), 
		'fr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "France").fillna(0)), 
		'ga':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Gabon").fillna(0)), 
		'gb':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "UK").fillna(0)), 
		'ge':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Georgia").fillna(0)), 
		'gf':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "French Guiana").fillna(0)), 
		'gh':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Ghana").fillna(0)), 
		'gl':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Greenland").fillna(0)), 
		'gm':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Gambia").fillna(0)), 
		'gn':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Guinea").fillna(0)), 
		'gq':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Equatorial Guinea").fillna(0)), 
		'gr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Greece").fillna(0)), 
		'gt':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Guatemala").fillna(0)), 
#		'gu':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Guam").fillna(0)), 
		'gw':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Guinea-Bissau").fillna(0)), 
		'gy':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Guyana").fillna(0)), 
		'hk':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Hong Kong").fillna(0)), 
		'hn':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Honduras").fillna(0)), 
		'hr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Croatia").fillna(0)), 
		'ht':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Haiti").fillna(0)), 
		'hu':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Hungary").fillna(0)), 
		'id':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Indonesia").fillna(0)), 
		'ie':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Ireland").fillna(0)), 
		'il':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Israel").fillna(0)), 
		'in':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "India").fillna(0)), 
		'iq':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Iraq").fillna(0)), 
		'ir':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Iran").fillna(0)), 
		'is':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Iceland").fillna(0)), 
		'it':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Italy").fillna(0)), 
		'jm':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Jamaica").fillna(0)), 
		'jo':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Jordan").fillna(0)), 
		'jp':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Japan").fillna(0)), 
		'ke':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Kenya").fillna(0)), 
		'kg':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Kyrgyzstan").fillna(0)), 
		'kh':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Cambodia").fillna(0)), 
		#'kp':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Korea, Democratic People’s Republic of").fillna(0)), 
		'kr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "S. Korea").fillna(0)), 
		'kw':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Kuwait").fillna(0)), 
		'kz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Kazakhstan").fillna(0)), 
		'la':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Laos").fillna(0)), 
		'lb':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Lebanon").fillna(0)), 
		'li':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Liechtenstein").fillna(0)), 
		'lk':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Sri Lanka").fillna(0)), 
		'lr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Liberia").fillna(0)), 
		#'ls':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Lesotho").fillna(0)), 
		'lt':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Lithuania").fillna(0)), 
		'lu':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Luxembourg").fillna(0)), 
		'lv':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Latvia").fillna(0)), 
		'ly':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Libya").fillna(0)), 
		'ma':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Morocco").fillna(0)), 
		'mc':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Monaco").fillna(0)), 
		'md':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Moldova").fillna(0)), 
		'me':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Montenegro").fillna(0)), 
		'mg':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Madagascar").fillna(0)), 
		'mk':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "North Macedonia").fillna(0)), 
		'ml':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Mali").fillna(0)), 
		'mm':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Myanmar").fillna(0)), 
		'mn':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Mongolia").fillna(0)), 
		'mo':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Macao").fillna(0)), 
		'mr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Mauritania").fillna(0)), 
		'mt':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Malta").fillna(0)), 
		'mu':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Mauritius").fillna(0)), 
		'mv':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Maldives").fillna(0)), 
#		'mw':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Malawi").fillna(0)), 
		'mx':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Mexico").fillna(0)), 
		'my':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Malaysia").fillna(0)), 
		'mz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Mozambique").fillna(0)), 
		'na':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Namibia").fillna(0)), 
		'ne':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Niger").fillna(0)), 
		'ng':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Nigeria").fillna(0)), 
		'ni':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Nicaragua").fillna(0)), 
		'nl':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Netherlands").fillna(0)), 
		'no':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Norway").fillna(0)), 
		'np':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Nepal").fillna(0)), 
		'nz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "New Zealand").fillna(0)), 
		'om':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Oman").fillna(0)), 
		'pa':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Panama").fillna(0)), 
		'pe':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Peru").fillna(0)), 
		'pg':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Papua New Guinea").fillna(0)), 
		'ph':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Philippines").fillna(0)), 
		'pk':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Pakistan").fillna(0)), 
		'pl':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Poland").fillna(0)), 
#		'pr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Puerto Rico").fillna(0)), 
		'ps':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Palestine").fillna(0)), 
		'pt':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Portugal").fillna(0)), 
		'py':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Paraguay").fillna(0)), 
		're':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Réunion").fillna(0)), 
		'ro':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Romania").fillna(0)), 
		'rs':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Serbia").fillna(0)), 
		'ru':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Russia").fillna(0)), 
		'rw':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Rwanda").fillna(0)), 
		'sa':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Saudi Arabia").fillna(0)), 
		'sc':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Seychelles").fillna(0)), 
		'sd':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Sudan").fillna(0)), 
		'se':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Sweden").fillna(0)), 
		'sg':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Singapore").fillna(0)), 
		'sh':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Saint Kitts and Nevis").fillna(0)), 
		'si':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Slovenia").fillna(0)), 
		'sk':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Slovakia").fillna(0)), 
		'sl':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Sierra Leone").fillna(0)), 
		'sm':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "San Marino").fillna(0)), 
		'sn':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Senegal").fillna(0)), 
		'so':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Somalia").fillna(0)), 
		'sr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Suriname").fillna(0)), 
		#'st':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Sao Tome and Principe").fillna(0)), 
		'sv':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "El Salvador").fillna(0)), 
		'sy':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Syria").fillna(0)), 
#		'sz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Swaziland").fillna(0)), 
		'td':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Chad").fillna(0)), 
		'tg':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Togo").fillna(0)), 
		'th':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Thailand").fillna(0)), 
#		'tj':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Tajikistan").fillna(0)), 
		'tl':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Timor-Leste").fillna(0)), 
	#	'tm':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Turkmenistan").fillna(0)), 
		'tn':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Tunisia").fillna(0)), 
		'tr':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Turkey").fillna(0)), 
		'tw':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Taiwan").fillna(0)), 
		'tz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Tanzania").fillna(0)), 
		'ua':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Ukraine").fillna(0)), 
		'ug':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Uganda").fillna(0)), 
		'us':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "USA").fillna(0)), 
		'uy':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Uruguay").fillna(0)), 
		'uz':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Uzbekistan").fillna(0)), 
		'va':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Vatican City").fillna(0)), 
		've':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Venezuela").fillna(0)), 
		'vn':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Vietnam").fillna(0)), 
		#'ye':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Yemen").fillna(0)), 
		'yt':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Mayotte").fillna(0)), 
		'za':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "South Africa").fillna(0)), 
		'zm':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Zambia").fillna(0)), 
		'zw':max(df[1]['TotalDeaths'].where(df[1]['Country,Other'] == "Zimbabwe").fillna(0))
        
        })

tc1.render_to_file('TotalDeaths.svg')




tc2 = pygal.maps.world.World()
tc2.title = 'Total Recovered'
tc2.add(str(int(max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "World").fillna(0)))) , {
		'ad':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Andorra").fillna(0)), 
		'ae':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "UAE").fillna(0)), 
		'af':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Afghanistan").fillna(0)), 
		'al':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Albania").fillna(0)), 
		'am':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Armenia").fillna(0)), 
		'ao':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Angola").fillna(0)), 
#		'aq':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Antarctica").fillna(0)), 
		'ar':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Argentina").fillna(0)), 
		'at':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Austria").fillna(0)), 
		'au':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Australia").fillna(0)), 
		'az':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Azerbaijan").fillna(0)), 
		'ba':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Bosnia and Herzegovina").fillna(0)), 
		'bd':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Bangladesh").fillna(0)), 
		'be':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Belgium").fillna(0)), 
		'bf':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Burkina Faso").fillna(0)), 
		'bg':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Bulgaria").fillna(0)), 
		'bh':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Bahrain").fillna(0)), 
		#'bi':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Burundi").fillna(0)), 
		'bj':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Benin").fillna(0)), 
		'bn':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Brunei").fillna(0)), 
		'bo':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Bolivia").fillna(0)), 
		'br':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Brazil").fillna(0)), 
		'bt':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Bhutan").fillna(0)), 
		'bw':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Botswana").fillna(0)), 
		'by':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Belarus").fillna(0)), 
		'bz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Belize").fillna(0)), 
		'ca':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Canada").fillna(0)), 
#		'cd':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Congo").fillna(0)), 
#		'cf':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Central African Republic").fillna(0)), 
		'cg':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Congo").fillna(0)), 
		'ch':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Switzerland").fillna(0)), 
#		'ci':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Cote d’Ivoire").fillna(0)), 
		'cl':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Chile").fillna(0)), 
		'cm':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Cameroon").fillna(0)), 
		'cn':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "China").fillna(0)), 
		'co':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Colombia").fillna(0)), 
		'cr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Costa Rica").fillna(0)), 
		'cu':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Cuba").fillna(0)), 
#		'cv':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Cape Verde").fillna(0)), 
		'cy':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Cyprus").fillna(0)), 
		'cz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Czechia").fillna(0)), 
		'de':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Germany").fillna(0)), 
		'dj':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Djibouti").fillna(0)), 
		'dk':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Denmark").fillna(0)), 
		'do':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Dominican Republic").fillna(0)), 
		'dz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Algeria").fillna(0)), 
		'ec':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Ecuador").fillna(0)), 
		'ee':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Estonia").fillna(0)), 
		'eg':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Egypt").fillna(0)), 
#		'eh':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Western Sahara").fillna(0)), 
		'er':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Eritrea").fillna(0)), 
		'es':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Spain").fillna(0)), 
		'et':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Ethiopia").fillna(0)), 
		'fi':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Finland").fillna(0)), 
		'fr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "France").fillna(0)), 
		'ga':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Gabon").fillna(0)), 
		'gb':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "UK").fillna(0)), 
		'ge':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Georgia").fillna(0)), 
		'gf':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "French Guiana").fillna(0)), 
		'gh':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Ghana").fillna(0)), 
		'gl':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Greenland").fillna(0)), 
		'gm':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Gambia").fillna(0)), 
		'gn':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Guinea").fillna(0)), 
		'gq':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Equatorial Guinea").fillna(0)), 
		'gr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Greece").fillna(0)), 
		'gt':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Guatemala").fillna(0)), 
#		'gu':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Guam").fillna(0)), 
		'gw':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Guinea-Bissau").fillna(0)), 
		'gy':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Guyana").fillna(0)), 
		'hk':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Hong Kong").fillna(0)), 
		'hn':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Honduras").fillna(0)), 
		'hr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Croatia").fillna(0)), 
		'ht':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Haiti").fillna(0)), 
		'hu':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Hungary").fillna(0)), 
		'id':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Indonesia").fillna(0)), 
		'ie':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Ireland").fillna(0)), 
		'il':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Israel").fillna(0)), 
		'in':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "India").fillna(0)), 
		'iq':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Iraq").fillna(0)), 
		'ir':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Iran").fillna(0)), 
		'is':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Iceland").fillna(0)), 
		'it':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Italy").fillna(0)), 
		'jm':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Jamaica").fillna(0)), 
		'jo':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Jordan").fillna(0)), 
		'jp':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Japan").fillna(0)), 
		'ke':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Kenya").fillna(0)), 
		'kg':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Kyrgyzstan").fillna(0)), 
		'kh':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Cambodia").fillna(0)), 
		#'kp':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Korea, Democratic People’s Republic of").fillna(0)), 
		'kr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "S. Korea").fillna(0)), 
		'kw':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Kuwait").fillna(0)), 
		'kz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Kazakhstan").fillna(0)), 
		'la':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Laos").fillna(0)), 
		'lb':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Lebanon").fillna(0)), 
		'li':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Liechtenstein").fillna(0)), 
		'lk':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Sri Lanka").fillna(0)), 
		'lr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Liberia").fillna(0)), 
		#'ls':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Lesotho").fillna(0)), 
		'lt':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Lithuania").fillna(0)), 
		'lu':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Luxembourg").fillna(0)), 
		'lv':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Latvia").fillna(0)), 
		'ly':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Libya").fillna(0)), 
		'ma':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Morocco").fillna(0)), 
		'mc':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Monaco").fillna(0)), 
		'md':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Moldova").fillna(0)), 
		'me':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Montenegro").fillna(0)), 
		'mg':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Madagascar").fillna(0)), 
		'mk':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "North Macedonia").fillna(0)), 
		'ml':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Mali").fillna(0)), 
		'mm':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Myanmar").fillna(0)), 
		'mn':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Mongolia").fillna(0)), 
		'mo':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Macao").fillna(0)), 
		'mr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Mauritania").fillna(0)), 
		'mt':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Malta").fillna(0)), 
		'mu':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Mauritius").fillna(0)), 
		'mv':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Maldives").fillna(0)), 
#		'mw':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Malawi").fillna(0)), 
		'mx':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Mexico").fillna(0)), 
		'my':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Malaysia").fillna(0)), 
		'mz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Mozambique").fillna(0)), 
		'na':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Namibia").fillna(0)), 
		'ne':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Niger").fillna(0)), 
		'ng':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Nigeria").fillna(0)), 
		'ni':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Nicaragua").fillna(0)), 
		'nl':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Netherlands").fillna(0)), 
		'no':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Norway").fillna(0)), 
		'np':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Nepal").fillna(0)), 
		'nz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "New Zealand").fillna(0)), 
		'om':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Oman").fillna(0)), 
		'pa':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Panama").fillna(0)), 
		'pe':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Peru").fillna(0)), 
		'pg':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Papua New Guinea").fillna(0)), 
		'ph':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Philippines").fillna(0)), 
		'pk':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Pakistan").fillna(0)), 
		'pl':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Poland").fillna(0)), 
#		'pr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Puerto Rico").fillna(0)), 
		'ps':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Palestine").fillna(0)), 
		'pt':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Portugal").fillna(0)), 
		'py':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Paraguay").fillna(0)), 
		're':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Réunion").fillna(0)), 
		'ro':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Romania").fillna(0)), 
		'rs':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Serbia").fillna(0)), 
		'ru':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Russia").fillna(0)), 
		'rw':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Rwanda").fillna(0)), 
		'sa':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Saudi Arabia").fillna(0)), 
		'sc':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Seychelles").fillna(0)), 
		'sd':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Sudan").fillna(0)), 
		'se':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Sweden").fillna(0)), 
		'sg':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Singapore").fillna(0)), 
		'sh':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Saint Kitts and Nevis").fillna(0)), 
		'si':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Slovenia").fillna(0)), 
		'sk':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Slovakia").fillna(0)), 
		'sl':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Sierra Leone").fillna(0)), 
		'sm':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "San Marino").fillna(0)), 
		'sn':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Senegal").fillna(0)), 
		'so':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Somalia").fillna(0)), 
		'sr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Suriname").fillna(0)), 
		#'st':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Sao Tome and Principe").fillna(0)), 
		'sv':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "El Salvador").fillna(0)), 
		'sy':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Syria").fillna(0)), 
#		'sz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Swaziland").fillna(0)), 
		'td':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Chad").fillna(0)), 
		'tg':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Togo").fillna(0)), 
		'th':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Thailand").fillna(0)), 
#		'tj':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Tajikistan").fillna(0)), 
		'tl':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Timor-Leste").fillna(0)), 
	#	'tm':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Turkmenistan").fillna(0)), 
		'tn':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Tunisia").fillna(0)), 
		'tr':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Turkey").fillna(0)), 
		'tw':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Taiwan").fillna(0)), 
		'tz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Tanzania").fillna(0)), 
		'ua':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Ukraine").fillna(0)), 
		'ug':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Uganda").fillna(0)), 
		'us':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "USA").fillna(0)), 
		'uy':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Uruguay").fillna(0)), 
		'uz':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Uzbekistan").fillna(0)), 
		'va':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Vatican City").fillna(0)), 
		've':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Venezuela").fillna(0)), 
		'vn':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Vietnam").fillna(0)), 
		#'ye':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Yemen").fillna(0)), 
		'yt':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Mayotte").fillna(0)), 
		'za':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "South Africa").fillna(0)), 
		'zm':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Zambia").fillna(0)), 
		'zw':max(df[1]['TotalRecovered'].where(df[1]['Country,Other'] == "Zimbabwe").fillna(0))
        
        })

tc2.render_to_file('TotalRecovered.svg')
